Add clipvision demo

diff --git a/venv/activate b/venv/activate
--- a/venv/activate
+++ b/venv/activate
@@ -35,3 +35,30 @@ export TT_METAL_LOGGER_LEVEL="ERROR"
 export ARCH_NAME="${ARCH_NAME:-wormhole_b0}"
 export TT_MLIR_HOME="$(pwd)/third_party/tt-mlir/src/tt-mlir/"
 export PATH=$TTMLIR_TOOLCHAIN_DIR/bin:${TT_MLIR_HOME}/build/bin:$PATH
+
+
+# Check if TT_MLIR_HOME is set
+if [[ -z "${TT_MLIR_HOME}" ]]; then
+    echo "Error: TT_MLIR_HOME environment variable is not set"
+    exit 1
+fi
+# Check if TT_METAL_RUNTIME_ROOT is set
+if [[ -z "${TT_METAL_RUNTIME_ROOT}" ]]; then
+    export TT_METAL_RUNTIME_ROOT="${TT_MLIR_HOME}/third_party/tt-metal/src/tt-metal"
+    echo "TT_METAL_RUNTIME_ROOT is not set. Setting it to ${TT_METAL_RUNTIME_ROOT}"
+fi
+# Confirm python3 exists
+if ! command -v python3 &> /dev/null; then
+    echo "Error: python3 could not be found"
+    exit 1
+fi
+# If ttnn module is not in PYTHONPATH, add it
+if [[ ":$PYTHONPATH:" != *":${TT_METAL_RUNTIME_ROOT}/ttnn:"* ]]; then
+    # This covers the corner case where PYTHONPATH is not set, avoids leading colon
+    export PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${TT_METAL_RUNTIME_ROOT}/ttnn"
+fi
+
+# If tracy module is not in PYTHONPATH, add it
+if [[ ":$PYTHONPATH:" != *":${TT_METAL_RUNTIME_ROOT}/tools/:"* ]]; then
+    export PYTHONPATH="${PYTHONPATH:+${PYTHONPATH}:}${TT_METAL_RUNTIME_ROOT}/tools/"
+fi
