Simplify/Improve/Cleanup CI yml changes for tt-forge-models tests usage
 - Reduce duplicated matrix generation (DRY!) from nighly/manual-test by moving to
   own yml file call-generate-forge-models-matrix.yml
 - It can now be used in push-main/pr-main too, to run few quick models
   for validating flow but most important validating config file, takes 5 mins
 - Add 'Validate Forge Models Tests test config file' step in call-test.yml to run
   for first matrix entry only (quick 15s job, but avoid duplication).
   Make it so tests are run even if validate step fails (still useful).
 - Update manual-test.yml to allow user specified mark for tt-forge-models
   so user can do things like "expected_passing and push" etc
 - Misc changes... rename jobs, remove redundant -q in collect tests job

diff --git a/.github/workflows/call-test.yml b/.github/workflows/call-test.yml
--- a/.github/workflows/call-test.yml
+++ b/.github/workflows/call-test.yml
@@ -205,14 +205,25 @@ jobs:
         apt-get update
         apt install -y libgl1 libglx-mesa0
 
+    # Ensure test_config.py for tt-forge-models test is valid, especially on PR's for uplifting tt-forge-models
+    # but still run tests even in case of failure here, will still treat overall job as failed.
+    - name: Validate Forge Models Tests test config file
+      if: ${{ matrix.build.name == 'run_forge_models_torch' && strategy.job-index == 0 }}
+      shell: bash
+      run: |
+        source venv/activate
+        pytest -vv tests/runner/test_models.py --validate-test-config
+
     - name: Collect Tests
+      if: success() || failure()
       shell: bash
       run: |
         source venv/activate
         echo "Collecting tests for group ${{ matrix.build.test_group_id || 1}}..."
-        pytest --collect-only -q ${{ env.BASE_PYTEST_CMD }}
+        pytest --collect-only ${{ env.BASE_PYTEST_CMD }}
 
     - name: Run tests
+      if: success() || failure()
       env:
         HF_HOME: /mnt/dockercache/huggingface
         GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
