Build docker image on push to main (#1732)
### Ticket

[Slack](https://tenstorrent.slack.com/archives/C08DJEGTNCR/p1760818006493579)

### Problem description
"Push to main" workflows expect that docker image already exists, but
this is not always true.
If we have multiple changes to docker structure pushed through different
PRs, main can have a new docker tag that is not yet built.

### What's changed
Update logic in "Push to main" workflows to allow for docker build if it
is missing.

Jobs in "test_forge_models_push" were running regardless on errors, also
updated that to not run if docker image is missing @kmabeeTT

### Checklist
- [ ] New/Existing tests provide coverage for changes

diff --git a/.github/workflows/call-build-docker.yml b/.github/workflows/call-build-docker.yml
--- a/.github/workflows/call-build-docker.yml
+++ b/.github/workflows/call-build-docker.yml
@@ -55,32 +55,6 @@ jobs:
             echo "Docker image does not exist, proceeding to build"
           fi
 
-      # Run the next steps only when pushed to main. Docker image must already exist, tag it as latest
-      - name: Log in to GitHub Container Registry
-        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-        uses: docker/login-action@v3
-        with:
-          registry: ghcr.io
-          username: ${{ github.repository_owner }}
-          password: ${{ github.token }}
-      - name: Set latest tag on the image
-        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
-        run: |
-          DOCKER_CI_IMAGE=${{ steps.check.outputs.docker-image }}
-          if [ -z "$DOCKER_CI_IMAGE" ]; then
-            echo "Error: steps.check.outputs.docker-image is not set"
-            exit 1
-          fi
-          DOCKER_TAG=$(echo $DOCKER_CI_IMAGE | sed 's/^.*://')
-
-          CI_IMAGE_NAME=$(echo $DOCKER_CI_IMAGE | sed 's/:.*//')
-          echo "Setting latest tag on the image $CI_IMAGE_NAME:$DOCKER_TAG"
-          skopeo copy "docker://$CI_IMAGE_NAME:$DOCKER_TAG" "docker://$CI_IMAGE_NAME:latest"
-
-          IRD_IMAGE_NAME=$(echo $DOCKER_CI_IMAGE | sed 's/:.*//' | sed 's/-ci-/-ird-/')
-          echo "Setting latest tag on the image $IRD_IMAGE_NAME:$DOCKER_TAG"
-          skopeo copy "docker://$IRD_IMAGE_NAME:$DOCKER_TAG" "docker://$IRD_IMAGE_NAME:latest"
-
   build-image:
     needs: check-if-docker-exist
     if: needs.check-if-docker-exist.outputs.docker-image == ''
@@ -121,3 +95,37 @@ jobs:
           echo "DOCKER_CI_IMAGE $DOCKER_CI_IMAGE"
           echo "docker-image=$DOCKER_CI_IMAGE" >> "$GITHUB_OUTPUT"
           echo "docker-image-base=$(echo $DOCKER_CI_IMAGE | sed 's/-ci-/-base-/')" >> "$GITHUB_OUTPUT"
+
+  set-latest-tag:
+    needs: [check-if-docker-exist, build-image]
+    runs-on: ubuntu-latest
+    # Run the next steps only when pushed to main, tag docker image as latest.
+    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') && (!failure())
+    steps:
+      - name: Log in to GitHub Container Registry
+        uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.repository_owner }}
+          password: ${{ github.token }}
+
+      - name: Set latest tag on the image
+        run: |
+          DOCKER_CI_IMAGE=${{ needs.check-if-docker-exist.outputs.docker-image }}
+          if [ -z "$DOCKER_CI_IMAGE" ]; then
+          echo "Using docker image from build-image job"
+            DOCKER_CI_IMAGE=${{ needs.build-image.outputs.docker-image }}
+          fi
+          if [ -z "$DOCKER_CI_IMAGE" ]; then
+            echo "Error: No docker image available from either check-if-docker-exist or build-image"
+            exit 1
+          fi
+          DOCKER_TAG=$(echo $DOCKER_CI_IMAGE | sed 's/^.*://')
+
+          CI_IMAGE_NAME=$(echo $DOCKER_CI_IMAGE | sed 's/:.*//')
+          echo "Setting latest tag on the image $CI_IMAGE_NAME:$DOCKER_TAG"
+          skopeo copy "docker://$CI_IMAGE_NAME:$DOCKER_TAG" "docker://$CI_IMAGE_NAME:latest"
+
+          IRD_IMAGE_NAME=$(echo $DOCKER_CI_IMAGE | sed 's/:.*//' | sed 's/-ci-/-ird-/')
+          echo "Setting latest tag on the image $IRD_IMAGE_NAME:$DOCKER_TAG"
+          skopeo copy "docker://$IRD_IMAGE_NAME:$DOCKER_TAG" "docker://$IRD_IMAGE_NAME:latest"
