Various updates for running test_models.py on CI and capture XML results
 - Add 308 passing tests to .test_durations
 - Initial CI ymls ported from tt-torch for running tt-forge-models
 - Add test-forge-models-matrix.json and use in tt-xla nightly CI
 - Add section to install system deps if running forge models tests

 - Some CI yml quality of life improvements
   - Make call-test.yml 120 min timeout overridable via input
   - Make verbosity dependent on --forked (gets percentages completion shown)
   - Add on-nightly.yml 10 job option (helpful for 300+ models)
   - Add pytest --durations=0 flag to show durations of tests

 - Initial changes to simplify/improve xml reporting from test_models.py
   - New marker to disable collection-time reporting, use runtime reporting instead
   - Remove skip_full_eval_test function, not needed anymore

 - Some initial changes to make forge_models_passing runnable via manual-test.yml,
   not great, this yml file doesn't fit too well with new tests here.

 - run_mode cleanup call "inference" instead of "eval", rename full-eval
   to full-inference

 - compiler_config in DynamicTester cleanup
 - Updates to --arch flag to take n150, p150 etc
 - Fix issue with --forked and use BringupStatus.UNKNOWN by default if not specified
 - switch to enum usage for bringup_status in test_config.py

 - Rename to common "bringup_status" and "reason" fields shared between NOT_SUPPORTED_SKIP and KNOWN_FAILURE_XFAIL
   - Update some bringup_status markers
   - fix model_info group convert to string

 - Improve dynamic reporting on tests by catching/handling exceptions/stderr. Catch exceptions, mark
   test as failed for various cases. Catch runtime errors too. Parse stderr to try
   and better differentiate between some failure cases.

diff --git a/.github/workflows/schedule-nightly.yml b/.github/workflows/schedule-nightly.yml
--- a/.github/workflows/schedule-nightly.yml
+++ b/.github/workflows/schedule-nightly.yml
@@ -15,6 +15,7 @@ on:
           - "4"
           - "5"
           - "8"
+          - "10"
   schedule:
     - cron: '0 0 * * *'
 
@@ -65,6 +66,7 @@ jobs:
     needs: [ set-inputs ]
     outputs:
       test-full-model-matrix: ${{ steps.generate-matrix.outputs.test-full-model-matrix}}
+      test-forge-models-matrix: ${{ steps.generate-forge-models-matrix.outputs.test-forge-models-matrix }}
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -100,6 +102,29 @@ jobs:
             python $SCRIPT_PATH $TEST_MATRIX_PATH "$TESTS_TO_PARALLELIZE" $TEST_GROUP_CNT  > modified-matrix.json
             echo "test-full-model-matrix=$(cat modified-matrix.json | jq -c)" >> $GITHUB_OUTPUT
 
+      - name: Generate tt-forge-models matrix
+        id: generate-forge-models-matrix
+        shell: bash
+        env:
+          TEST_GROUP_CNT: "10"
+        run: |
+            SCRIPT_PATH=".github/scripts/generate_test_model_matrix.py"
+            TEST_MATRIX_PATH=".github/workflows/test-forge-models-matrix.json"
+            TESTS_TO_PARALLELIZE='[
+              {
+                "runs-on": "n150",
+                "name": "run_forge_models_torch",
+                "dir": "./tests/runner/test_models.py"
+              },
+              {
+                "runs-on": "p150",
+                "name": "run_forge_models_torch",
+                "dir": "./tests/runner/test_models.py"
+              }
+            ]'
+            python $SCRIPT_PATH $TEST_MATRIX_PATH "$TESTS_TO_PARALLELIZE" $TEST_GROUP_CNT  > modified-matrix.json
+            echo "test-forge-models-matrix=$(cat modified-matrix.json | jq -c)" >> $GITHUB_OUTPUT
+
   test_full_model:
     uses: ./.github/workflows/call-test.yml
     secrets: inherit
@@ -114,11 +139,28 @@ jobs:
       artifact_release_run_id: ${{ needs.build-ttxla.outputs.artifacts_run_id }}
       wheel_release_artifact_name: ${{ needs.build-ttxla.outputs.wheel_artifact_name }}
 
+  # This is a single test job that runs all passing tt-forge-models tests.
+  test_full_model_forge_models_passing:
+    uses: ./.github/workflows/call-test.yml
+    secrets: inherit
+    needs: [ build-image, build-ttxla, generate-matrix ]
+    # This ensures the job runs regardless of success or failure of `nightly_tests`:
+    if: success() || failure()
+    with:
+      timeout_minutes: 180
+      docker_image: ${{ needs.build-image.outputs.docker-image }}
+      test_mark: 'expected_passing'
+      test_matrix: ${{ needs.generate-matrix.outputs.test-forge-models-matrix }}
+      use-shared-runners: false # Run full model tests on Civ1
+      artifact_release_run_id: ${{ needs.build-ttxla.outputs.artifacts_run_id }}
+      wheel_release_artifact_name: ${{ needs.build-ttxla.outputs.wheel_artifact_name }}
+
   fail-notify:
     if: always()
     needs:
       - nightly_tests
       - test_full_model
+      - test_full_model_forge_models_passing
       - build-image
       - build-ttxla
     runs-on: Ubuntu-latest
